services:
  frontend:
    build:
      context: frontend_rep
    ports:
      - 3001:3001
    networks:
      - app-network
    depends_on:
      - backend
    # command: ['npm', 'run', 'start']
    command:
      ['./usr/wait-for-it.sh', 'backend:3000', '--', 'npm', 'run', 'start']
  backend:
    build:
      context: backend_rep

    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://user:password@db:3306/ojt
      JWT_KEY: JWT_KEY
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - db
    expose:
      - 3000
    command:
      [
        './usr/wait-for-it.sh',
        'db:3306',
        '--',
        'npm',
        'run',
        'start:pushdb:prod',
      ]
    # command: ['./usr/wait-for', 'db:3306', '--', 'npm', 'run', 'start:prod']

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ojt
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    expose:
      - 3306
    ports:
      - 3306:3306
volumes:
  db-data:
networks:
  app-network:
    driver: bridge
